#!/bin/bash
# Deployment script for Setback game server
# Usage: ./deploy.sh <instance-ip>

set -euo pipefail

DEPLOY_USER="root"
APP_DIR="/opt/setback"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.production"
REMOTE_DEPLOY_SCRIPT="$SCRIPT_DIR/remote-deploy.sh"
TEMP_DIR=""
INSTANCE_IP=""
SSH_KEY=""
PUBLIC_BASE_URL=""
PUBLIC_HOST=""

log() {
    printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$1"
}

die() {
    echo "ERROR: $1" >&2
    exit 1
}

usage() {
    cat <<EOF
Usage: $0 <instance-ip>
Example: $0 54.123.45.67
EOF
    exit 1
}

cleanup() {
    if [ -n "${TEMP_DIR:-}" ] && [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"
    fi
}

require_file() {
    local path=$1
    [ -f "$path" ] || die "Required file not found: $path"
}

pick_ssh_key() {
    if [ -f "$HOME/.ssh/setback-do-key" ]; then
        SSH_KEY="$HOME/.ssh/setback-do-key"
    else
        die "No deployment SSH key found at ~/.ssh/setback-do-key"
    fi
}

load_env() {
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a

    PUBLIC_BASE_URL="${BASE_URL:-}"
}

derive_public_host() {
    local raw_url host
    raw_url="${PUBLIC_BASE_URL:-}"
    host="${raw_url#https://}"
    host="${host#http://}"
    host="${host%%/*}"
    host="${host%%:*}"

    [ -n "$host" ] || die "Could not derive public host from BASE_URL=$PUBLIC_BASE_URL"
    PUBLIC_HOST="$host"
}

validate_env() {
    require_file "$ENV_FILE"
    load_env
    derive_public_host

    [ "${APP_ENV:-}" = "prod" ] || die "APP_ENV must be set to prod in $ENV_FILE"
    [ "${AUTO_CREATE_SCHEMA:-}" = "false" ] || die "AUTO_CREATE_SCHEMA must be false in $ENV_FILE"
    [ "${ENABLE_DEV_AUTH:-}" = "false" ] || die "ENABLE_DEV_AUTH must be false in $ENV_FILE"
    [ -n "${BASE_URL:-}" ] || die "BASE_URL must be set in $ENV_FILE"
    [ -n "${CLIENT_ORIGIN:-}" ] || die "CLIENT_ORIGIN must be set in $ENV_FILE"
    [ -n "${SESSION_SECRET:-}" ] || die "SESSION_SECRET must be set in $ENV_FILE"
    [ -n "${JWT_SECRET:-}" ] || die "JWT_SECRET must be set in $ENV_FILE"

    [ "$SESSION_SECRET" != "CHANGE_THIS_TO_RANDOM_STRING" ] || die "SESSION_SECRET is still a placeholder"
    [ "$JWT_SECRET" != "CHANGE_THIS_TO_A_DIFFERENT_RANDOM_STRING" ] || die "JWT_SECRET is still a placeholder"
    require_file "$REMOTE_DEPLOY_SCRIPT"
}

make_temp_dir() {
    TEMP_DIR=$(mktemp -d)
    trap cleanup EXIT
}

write_caddyfile() {
    cat > "$TEMP_DIR/Caddyfile" <<EOF
# Generated by deploy/deploy.sh from BASE_URL in deploy/.env.production
${PUBLIC_HOST} {
    reverse_proxy web:80

    log {
        output stdout
        format console
    }
}
EOF
}

prepare_release_bundle() {
    log "Preparing deployment package"
    rsync -av \
        --exclude='.git' \
        --exclude='.venv' \
        --exclude='__pycache__' \
        --exclude='*.pyc' \
        --exclude='.pytest_cache' \
        --exclude='.mypy_cache' \
        --exclude='.ruff_cache' \
        --exclude='deploy' \
        --exclude='.project' \
        "$REPO_DIR/" "$TEMP_DIR/"

    write_caddyfile
}

remote_shell() {
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$DEPLOY_USER@$INSTANCE_IP" "$@"
}

sync_release_bundle() {
    log "Preparing remote directory"
    remote_shell "mkdir -p $APP_DIR"

    log "Copying application files"
    rsync -av -e "ssh -i $SSH_KEY -o StrictHostKeyChecking=no" \
        "$TEMP_DIR/" \
        "$DEPLOY_USER@$INSTANCE_IP:$APP_DIR/"

    log "Copying production environment"
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no \
        "$ENV_FILE" \
        "$DEPLOY_USER@$INSTANCE_IP:$APP_DIR/.env"
}

run_remote_deploy() {
    log "Running remote deployment"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no \
        "$DEPLOY_USER@$INSTANCE_IP" \
        "APP_DIR='$APP_DIR' bash -s" < "$REMOTE_DEPLOY_SCRIPT"
}

main() {
    [ $# -eq 1 ] || usage

    INSTANCE_IP=$1
    pick_ssh_key
    validate_env
    make_temp_dir

    log "Deploying to $INSTANCE_IP"
    prepare_release_bundle
    sync_release_bundle
    run_remote_deploy

    log "Deployment complete"
    echo "Access your server at: ${PUBLIC_BASE_URL:-http://$INSTANCE_IP}"
    echo "To check logs: ssh -i $SSH_KEY $DEPLOY_USER@$INSTANCE_IP 'cd $APP_DIR && docker compose logs -f'"
}

main "$@"
